log_format lab_json escape=json '{'
    '"timestamp":"$time_iso8601",'
    '"remoteAddress":"$remote_addr",'
    '"method":"$request_method",'
    '"uri":"$request_uri",'
    '"status":$status,'
    '"durationSeconds":$request_time,'
    '"upstream":"$upstream_addr",'
    '"instanceId":"$sent_http_x_instance_id",'
    '"correlationId":"$sent_http_x_correlation_id"'
    '}';

upstream orders_api {
    server orders-api-1:8080;
    server orders-api-2:8080;
    keepalive 16;
}

server {
    listen 8080;
    server_name _;

    access_log /var/log/nginx/access.log lab_json;

    location = /nginx-health {
        access_log off;
        default_type text/plain;
        return 200 "healthy\n";
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Correlation-ID $http_x_correlation_id;
        proxy_connect_timeout 3s;
        proxy_read_timeout 15s;
        proxy_pass http://orders_api;
    }
}
