apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - infrastructure-endpoints.yaml
  - connectivity-job.yaml
images:
  - name: local-distributed-lab/orders-api
    newTag: milestone-7
  - name: local-distributed-lab/orders-worker
    newTag: milestone-7
patches:
  - target:
      kind: Deployment
      name: orders-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: orders-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: orders-migrations-m7
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
