apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orders-lab
resources:
  - ../../base
  - infrastructure-endpoints.yaml
  - connectivity-job.yaml
images:
  - name: local-distributed-lab/orders-api
    newTag: milestone-43-saga-migration
  - name: local-distributed-lab/orders-worker
    newTag: milestone-44-bestsellers
  - name: local-distributed-lab/payments-service
    newTag: milestone-34-profiling-fix
  - name: local-distributed-lab/catalog-service
    newTag: milestone-44-bestsellers
  - name: local-distributed-lab/inventory-service
    newTag: milestone-43-commit-release
  - name: local-distributed-lab/cart-service
    newTag: milestone-42-cart-redis-timeout-fix
  - name: local-distributed-lab/storefront-service
    newTag: milestone-45-storefront-token-fix
patches:
  - target:
      kind: Rollout
      name: orders-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: orders-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: payments-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: orders-migrations-m7
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: payments-migrations-m12
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: catalog-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: catalog-seed-m40
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: inventory-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: inventory-migrations-m41
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Job
      name: inventory-seed-m41
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: cart-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: storefront-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
